name: SimplePipeline

on:
  push:
    branches: [main]

jobs:
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repostitory
        uses: actions/checkout@v2
      - name: Install Dependecies
        run: |
          echo "Running Installing Dependencies..."
          npm install
      - name: Run Linting
        run: |
          echo "Running Linting tests.."
          npm run lint
        env:
          CI: true
  securityCheck:
    name: Secutrity Check
    runs-on: ubuntu-latest
    steps:
      - name: Check for Security
        run: |
          echo "Running Security Checks.."
          sleep 5s;
          echo "Running Security Checks.. 1"
          sleep 5s;
          echo "Running Security Checks.. 2"
          sleep 5s;
          echo "Running Security Checks.. 3"
          sleep 5s;
